### ISSUE TITLE
Issue with patch file

### ISSUE THREAD

**Issue by JaCoVol** [deadSEKTR/FC5-RESISTANCE-MOD-DEVELOPER-EDITION#1]
It says wrong data in patch.fat.rtrobak. deleting it instead says "correct patch.fat or patch.dat was not found" any way I can fix this?

**Comment by deadSEKTR** [comment]
Delete the existing patch.fat.rtrobak, and when it says 'correct xxx not found' just select FarCry5.exe located in the game's installation directory. The mod manager will automatically try to find patch.fat & patch.dat inside the directory.
